#-*-Makefile-*- for examples of feram
# Time-stamp: <07/12/30 11:10:50 takeshi>
# Author: Takeshi NISHIMATSU
##
all-potential-surface.ps: all-potential-surface.gp
	./$<

clean:
	rm -f feram.* *.ps *.pdf *lambda*.dat
