#-*-Makefile-*- for examples of feram
# Time-stamp: <2007-12-14 02:35:09 takeshi>
# Author: Takeshi NISHIMATSU
##
feram.log: externalE.sh ../feram
	./$<
clean:
	rm -f *.coord *.dat core* *.eps *.param *.avg *.log *.out *.err *.ps externalE???K-* externalE???K+*
